//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLECalApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class menu_styles
    {
        public int id { get; set; }
        public string styleName { get; set; }
        public Nullable<int> isDeleted { get; set; }
    }
}
