//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLECalApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class modeEMail
    {
        public int eid { get; set; }
        public string tomailids { get; set; }
        public string ccmailids { get; set; }
        public int isdeleted { get; set; }
        public Nullable<System.DateTime> createdon { get; set; }
        public int createdby { get; set; }
        public string MessageMode { get; set; }
    }
}
