//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLECalApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class PINGHANDLER_tbl
    {
        public int PID { get; set; }
        public Nullable<int> MachineID { get; set; }
        public Nullable<int> Pingcount { get; set; }
        public string CorrectedDate { get; set; }
        public string IPADDRESS { get; set; }
    }
}
