//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLECalApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblactivity
    {
        public int ActivityId { get; set; }
        public string ActivityName { get; set; }
        public string ActivityDescc { get; set; }
        public int Isdeleted { get; set; }
        public System.DateTime Createdon { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> PlantId { get; set; }
        public Nullable<int> ShopId { get; set; }
        public Nullable<int> CellId { get; set; }
        public Nullable<int> MachineId { get; set; }
        public string OptionalAct { get; set; }
        public Nullable<int> ProcessId { get; set; }
    }
}
