//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLECalApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployee
    {
        public int Eid { get; set; }
        public Nullable<int> EmpId { get; set; }
        public string EmpName { get; set; }
        public string EmpDesignation { get; set; }
        public Nullable<int> EmpRole { get; set; }
        public Nullable<int> PlantId { get; set; }
        public Nullable<int> ShopId { get; set; }
        public Nullable<int> CellId { get; set; }
        public string CantactNo { get; set; }
        public string EmailId { get; set; }
        public int Isdeleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    }
}
