//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLECalApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblModeBackUp
    {
        public int modebackUpId { get; set; }
        public Nullable<int> modeId { get; set; }
        public Nullable<int> machineId { get; set; }
        public string mode { get; set; }
        public Nullable<System.DateTime> insertedOn { get; set; }
        public Nullable<int> insertedBy { get; set; }
        public Nullable<System.DateTime> modifiedOn { get; set; }
        public Nullable<int> modifiedBy { get; set; }
        public string correctedDate { get; set; }
        public Nullable<int> isDeleted { get; set; }
        public Nullable<System.DateTime> startTime { get; set; }
        public Nullable<System.DateTime> endTime { get; set; }
        public string colorCode { get; set; }
        public Nullable<int> isCompleted { get; set; }
        public Nullable<int> durationInSec { get; set; }
        public Nullable<int> modeMonth { get; set; }
        public Nullable<int> modeYear { get; set; }
        public Nullable<int> modeWeekNumber { get; set; }
        public Nullable<int> modeQuarter { get; set; }
    }
}
