//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLECalApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbloeeDashBoardVBackUp
    {
        public int oeeVariablesBackUpId { get; set; }
        public Nullable<int> oeeVariablesId { get; set; }
        public Nullable<int> plantId { get; set; }
        public Nullable<int> shopId { get; set; }
        public Nullable<int> cellId { get; set; }
        public Nullable<int> wcid { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public Nullable<double> minorLosses { get; set; }
        public Nullable<double> blue { get; set; }
        public Nullable<double> green { get; set; }
        public Nullable<double> settingTime { get; set; }
        public Nullable<double> roaLossess { get; set; }
        public Nullable<double> downTimeBreakdown { get; set; }
        public Nullable<double> summationOfSCTvsPP { get; set; }
        public Nullable<double> scrapQtyTime { get; set; }
        public Nullable<double> reWOTime { get; set; }
        public string loss1Name { get; set; }
        public Nullable<int> loss1Value { get; set; }
        public string loss2Name { get; set; }
        public Nullable<int> loss2Value { get; set; }
        public string loss3Name { get; set; }
        public Nullable<int> loss3Value { get; set; }
        public string loss4Name { get; set; }
        public Nullable<int> loss4Value { get; set; }
        public string loss5Name { get; set; }
        public Nullable<int> loss5Value { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<int> isDeleted { get; set; }
    }
}
