//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLECalApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblolecaldetail
    {
        public int oleid { get; set; }
        public Nullable<int> opid { get; set; }
        public Nullable<int> opWorkingDuration { get; set; }
        public Nullable<int> lossDuration { get; set; }
        public Nullable<int> MachineId { get; set; }
        public string CorrectedDate { get; set; }
        public string OTTime { get; set; }
        public Nullable<int> shift { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public int Isdeleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<double> Blue { get; set; }
        public Nullable<double> Green { get; set; }
        public Nullable<double> SettingTime { get; set; }
        public Nullable<double> ROALossess { get; set; }
        public Nullable<double> SummationOfSCTvsPP { get; set; }
        public Nullable<double> ScrapQtyTime { get; set; }
        public Nullable<double> ReWOTime { get; set; }
    }
}
