//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLECalApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTcfApprovedMaster
    {
        public int tcfApprovedMasterId { get; set; }
        public Nullable<int> tcfModuleId { get; set; }
        public string firstApproverToList { get; set; }
        public string firstApproverCcList { get; set; }
        public string secondApproverToList { get; set; }
        public string secondApproverCcList { get; set; }
        public Nullable<int> plantId { get; set; }
        public Nullable<int> shopId { get; set; }
        public Nullable<int> cellId { get; set; }
        public Nullable<int> isDeleted { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> modifiedOn { get; set; }
        public Nullable<int> modifiedBy { get; set; }
    }
}
