//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLECalApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTempCalculate
    {
        public int whmiid { get; set; }
        public int PDelQty { get; set; }
        public int PProcQty { get; set; }
        public int CDelQty { get; set; }
        public int CProcQty { get; set; }
    }
}
