//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLECalApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblunasignedwo
    {
        public int Uawoid { get; set; }
        public System.DateTime Starttime { get; set; }
        public System.DateTime Endtime { get; set; }
        public int Isdeleted { get; set; }
        public string Correcteddate { get; set; }
        public string Createdon { get; set; }
        public int Createdby { get; set; }
        public string WorkOrderNo { get; set; }
        public string PartNo { get; set; }
        public string OprationNo { get; set; }
        public string Project { get; set; }
        public string ProdFai { get; set; }
        public string WorkOrderQty { get; set; }
        public string ProcessedQty { get; set; }
        public string DeliveryQty { get; set; }
        public int SendApprove { get; set; }
        public int Acceptreject { get; set; }
        public int Isupdate { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string Shiftid { get; set; }
        public string Operatorid { get; set; }
        public Nullable<int> Machineid { get; set; }
        public Nullable<int> JobFinish { get; set; }
        public Nullable<int> PartialFinish { get; set; }
        public Nullable<int> GenericWo { get; set; }
        public Nullable<int> ReWork { get; set; }
        public Nullable<int> IsSplit { get; set; }
        public Nullable<int> Loperatorid { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Isworkinprogress { get; set; }
        public Nullable<int> Isworkorder { get; set; }
        public Nullable<System.DateTime> Pestarttime { get; set; }
        public string Ddlworkcenter { get; set; }
        public Nullable<int> Holdcodeid { get; set; }
        public string Holdcodereason { get; set; }
        public int rejectreasonid { get; set; }
        public int GenericCodeid { get; set; }
        public string GenericCodereason { get; set; }
        public int isStart { get; set; }
        public int isSplitDuration { get; set; }
        public int ApprovalLevel { get; set; }
        public int AcceptReject1 { get; set; }
        public int RejectReason { get; set; }
        public int RejectReason1 { get; set; }
        public int UpdateLevel { get; set; }
        public int isBlank { get; set; }
        public int IsPending { get; set; }
    }
}
